name = "Capse"
uuid = "994f66c3-d2c7-4ba6-88fb-4a10f50800ba"
authors = ["marcobonici <bonici.marco@gmail.com>"]
version = "0.3.0"

[deps]
AbstractCosmologicalEmulators = "c83c1981-e5c4-4837-9eb8-c9b1572acfc6"
FastChebInterp = "cf66c380-9a80-432c-aff8-4f9c79c0bdde"

[compat]
AbstractCosmologicalEmulators = "0.3.1"
